In [ ]:
#Question1
'''

'''

In [ ]:
#Question3
'''
Array module helps us to create light arrays for example 1-D arrays. They are also 
obsolete in nature i.e. we can only store one type of variables in them. There is
no support for complex matrix caluculations.
Numpy is much more powerful than normal arrays. We can create higher dimension arrays
easily. We can also store different datatypes in a single array. It has a lot of 
functions which help us to do matrix based calculations efficiently.
'''

In [ ]:
#Question4
'''
An empty array initializes an array of given dimension having the elements in the array
as userdefined datatype. The elements are random numbers and are extremely small but not
exactly zero if not defined by the user.

A ones array intitializes an array of user defined dimension but here all the elements 
in the array/matrix have a value 1.

A zeros array does the same as ones array but here all the elements in the array/matrix 
are initialized with a value 0.
'''

In [ ]:
#Question5
'''
The callable argument is the function argument in numpy.fromfunction() function it helps
us to define a logic based on which the elements of the matrix or array are populated. 
'''

In [ ]:
#Question6
'''
When we add a scalar to an array or matrix the scalar value simply gets added to each element 
in the array. Thus if arr([1,2],[3,4])+n => arr([1+n,2+n],[3+n,4+n]).
'''

In [ ]:
#Question7
'''
Yes we can use array to scalar combined operation assign operators the outcome is same as the 
normal scalar addition to an array. This results in a inplace addition or muliplication and the 
original array gets replaced by the new array value.
'''

In [ ]:
#Question8
'''
Once we create a numpy array with a fixed length, if we try and add a new string of greater length 
than the assigned length it will reject the part of the string greater than the length alloted to 
the elements of the array.
'''

In [ ]:
#Question9
'''
When we use addition or multiplication operator on two arrays it gives us element wise
addition and multiplication respectively. To multiply two arrays as a cross product we 
use the funtion numpy.matmul(array1,array2).

'''

In [52]:
import numpy as np

arr1 = np.empty([2,2]) + 9.4
arr2 = np.zeros([2,2])
arr3 = np.ones([2,2])

print(arr1)
#print(arr2)
#print(arr3)

[[9.4 9.4]
 [9.4 9.4]]


In [70]:
arr1 = np.array([[1,2],[2,1]])
arr2 = np.array([[3,4],[4,3]])

arrf = 
print(arrf)

arrf1 = arr1 + arr2 
print(arrf1)

[[3 8]
 [8 3]]
[[4 6]
 [6 4]]


[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 8.30030285e-321]
 [1.24610723e-306 1.29061142e-306 5.53353523e-322]]


In [3]:
import array 

l = arr

TypeError: 'module' object is not callable